name = "guber-v0"
main = "src/worker.ts"
compatibility_date = "2023-11-21"

[[d1_databases]]
binding = "DB"
database_name = "guber-db"
database_id = "5f5d9a0a-b02c-44cf-88d8-91a48c720e99"

[[queues.producers]]
queue = "guber-bus"
binding = "GUBER_BUS"

[[queues.consumers]]
queue = "guber-bus"

[vars]
# Add your Cloudflare API token as a secret: wrangler secret put CLOUDFLARE_API_TOKEN

[triggers]                                      
crons = ["* * * * *"] 
