name = "guber-v0"
main = "src/worker.ts"
compatibility_date = "2023-11-21"

[[d1_databases]]
binding = "DB"
database_name = "guber-db"
database_id = "b21bb1bc-6d87-43b8-9c36-c31cbad47dbb"

[[queues.producers]]
queue = "d1-provisioning-queue"
binding = "D1_QUEUE"

[[queues.consumers]]
queue = "d1-provisioning-queue"

[vars]
# Add your Cloudflare API token as a secret: wrangler secret put CLOUDFLARE_API_TOKEN
