name = "guber-v0"
main = "src/worker.ts"
compatibility_date = "2023-11-21"

[[d1_databases]]
binding = "DB"
database_name = "guber-db"
database_id = "d388482f-3c4b-44b3-8272-2f5e99ea74f3"

[[queues.producers]]
queue = "guber-bus"
binding = "GUBER_BUS"

[[queues.consumers]]
queue = "guber-bus"

[vars]
# Add your Cloudflare API token as a secret: wrangler secret put CLOUDFLARE_API_TOKEN
# Add your domain as a secret: wrangler secret put GUBER_DOMAIN

[triggers]                                      
crons = ["* * * * *"] 
