apiVersion: cf.guber.proc.io/v1
kind: Worker
metadata:
  name: example-worker
spec:
  name: example-worker
  scriptUrl: "https://github.com/polvi/first-worker/releases/download/v0.0.2/index.js"
  compatibility_date: "2025-11-27"
