apiVersion: cf.guber.proc.io/v1
kind: WorkerScriptDeployment
metadata:
  name: hello-world-worker-v2-deployment
spec:
  scriptName: hello-world-worker
  strategy: percentage
  versions:
    - version_id: "a443fe1f-4ead-4cc4-995c-88144ff87ac4",
      percentage: 100
  annotations:
    message: "Deploying version 2.0 to production"
    triggered_by: "guber-example"
  dependencies:
    - kind: WorkerScriptVersion
      name: hello-world-worker-v2
      group: cf.guber.proc.io
